### STAGE 1: Build ###
FROM node:12.11-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g @angular/cli@7.3.9
COPY . .
RUN ng build --prod --aot --buildOptimizer
### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/swagger-ui /usr/share/nginx/html
